// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2e0kw8NPiFnJj7FGFUWzIMx8vTRxcW-w',
    appId: '1:644186686014:web:07897973fb69284f22476f',
    messagingSenderId: '644186686014',
    projectId: 'chatting-app-b7e6b',
    authDomain: 'chatting-app-b7e6b.firebaseapp.com',
    storageBucket: 'chatting-app-b7e6b.firebasestorage.app',
    measurementId: 'G-S7YDHVCQZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUrnhqN3AEj6lKtqElBdAY7Q4yrJM09A',
    appId: '1:644186686014:android:635c58dda432806e22476f',
    messagingSenderId: '644186686014',
    projectId: 'chatting-app-b7e6b',
    storageBucket: 'chatting-app-b7e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uLYPTDfyNJ3HcqzLEszlC_ktgyEdpSw',
    appId: '1:644186686014:ios:e11f003bcf4bcaa222476f',
    messagingSenderId: '644186686014',
    projectId: 'chatting-app-b7e6b',
    storageBucket: 'chatting-app-b7e6b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uLYPTDfyNJ3HcqzLEszlC_ktgyEdpSw',
    appId: '1:644186686014:ios:e11f003bcf4bcaa222476f',
    messagingSenderId: '644186686014',
    projectId: 'chatting-app-b7e6b',
    storageBucket: 'chatting-app-b7e6b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2e0kw8NPiFnJj7FGFUWzIMx8vTRxcW-w',
    appId: '1:644186686014:web:ae7230b4d7c9259e22476f',
    messagingSenderId: '644186686014',
    projectId: 'chatting-app-b7e6b',
    authDomain: 'chatting-app-b7e6b.firebaseapp.com',
    storageBucket: 'chatting-app-b7e6b.firebasestorage.app',
    measurementId: 'G-8N1G7MQWG2',
  );
}
